name = "jorh-redirect"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "LINKS_KV"
id = "YOUR_KV_NAMESPACE_ID"
preview_id = "YOUR_KV_PREVIEW_NAMESPACE_ID"

[[queues.producers]]
binding = "CLICK_QUEUE"
queue = "jorh-click-events"

[dev]
port = 3003
